from django.urls import path

from .views import (
    ItemPedidoCadastrar,
    ItemPedidoEditar,
    ItemPedidoExcluir,
    PagamentoCadastrar,
    PagamentoEditar,
    PagamentoApiAprovar,
    PagamentoApiCancelar,
    PagamentoApiRecusar,
    PagamentoApiSimular,
    PedidoApiCadastrar,
    PedidoApiDeletar,
    PedidoApiDetalharAtualizar,
    PedidoApiFinalizarProduto,
    PedidoApiListar,
    PedidoCadastrar,
    PedidoDetalhar,
    PedidoEditar,
    PedidoExcluir,
    PedidoListar,
)

urlpatterns = [
    path('', PedidoListar.as_view(), name='pedido_listar'),
    path('api/listar/', PedidoApiListar.as_view(), name='pedido_api_listar'),
    path('api/novo/', PedidoApiCadastrar.as_view(), name='pedido_api_cadastrar'),
    path('api/finalizar-produto/', PedidoApiFinalizarProduto.as_view(), name='pedido_api_finalizar_produto'),
    path('api/editar/<int:pk>/', PedidoApiDetalharAtualizar.as_view(), name='pedido_api_editar'),
    path('api/deletar/<int:pk>/', PedidoApiDeletar.as_view(), name='pedido_api_deletar'),
    path('novo/', PedidoCadastrar.as_view(), name='pedido_cadastrar'),
    path('<int:pedido_id>/api/pagamento/', PagamentoApiSimular.as_view(), name='pagamento_api_simular'),
    path('<int:pedido_id>/api/pagamento/aprovar/', PagamentoApiAprovar.as_view(), name='pagamento_api_aprovar'),
    path('<int:pedido_id>/api/pagamento/recusar/', PagamentoApiRecusar.as_view(), name='pagamento_api_recusar'),
    path('<int:pedido_id>/api/pagamento/cancelar/', PagamentoApiCancelar.as_view(), name='pagamento_api_cancelar'),
    path('<int:id>/', PedidoDetalhar.as_view(), name='pedido_detalhar'),
    path('<int:id>/editar/', PedidoEditar.as_view(), name='pedido_editar'),
    path('<int:id>/excluir/', PedidoExcluir.as_view(), name='pedido_excluir'),
    path('<int:pedido_id>/itens/novo/', ItemPedidoCadastrar.as_view(), name='item_pedido_cadastrar'),
    path('itens/<int:item_id>/editar/', ItemPedidoEditar.as_view(), name='item_pedido_editar'),
    path('itens/<int:item_id>/excluir/', ItemPedidoExcluir.as_view(), name='item_pedido_excluir'),
    path('<int:pedido_id>/pagamento/novo/', PagamentoCadastrar.as_view(), name='pagamento_cadastrar'),
    path('pagamentos/<int:pagamento_id>/editar/', PagamentoEditar.as_view(), name='pagamento_editar'),
]
