# Generated by Django 6.0.5 on 2026-06-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_sku', models.CharField(max_length=50, unique=True)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('garantia_meses', models.PositiveIntegerField(default=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categoria')),
            ],
        ),
    ]
