# Generated by Django 6.0.5 on 2026-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_sku',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
